import type { OperationalMapOverview, OperationalMapPoint } from "./types";

export const buildingPendingDemoPoints: OperationalMapPoint[] = [
  {
    id: "b0100000-0000-4000-8000-000000000001",
    category: "building_pending",
    title: "Edificio comunitario demo 01",
    locationLabel: "Floridablanca, Santander",
    latitude: 7.071,
    longitude: -73.099,
    coordinatePrecision: "approximate",
    verificationStatus: "under_review",
    relatedDisasterId: null,
    description: "Inspección demostrativa pendiente. No declara que el edificio sea inseguro, esté colapsado ni tenga personas en su interior.",
    source: {
      name: "Inventario estructural frontend demo",
      sourceType: "integration",
      url: null,
    },
    updatedAt: "2026-08-12T18:27:00.000Z",
  },
  {
    id: "b0100000-0000-4000-8000-000000000002",
    category: "building_pending",
    title: "Bloque institucional demo 02",
    locationLabel: "Girón, Santander",
    latitude: 7.072,
    longitude: -73.169,
    coordinatePrecision: "approximate",
    verificationStatus: "unverified",
    relatedDisasterId: null,
    description: "Edificio demostrativo sin inspección registrada. Su seguridad estructural todavía no ha sido determinada.",
    source: {
      name: "Inventario estructural frontend demo",
      sourceType: "integration",
      url: null,
    },
    updatedAt: "2026-08-12T18:21:00.000Z",
  },
];

export const operationalMapDemoData: OperationalMapOverview = {
  summary: {
    missingPerson: 2,
    collectionCenter: 2,
    collectionPoint: 0,
    rubbleReviewed: 2,
    rubblePending: 2,
    buildingPending: 2,
    communityMeal: 0,
    temporaryShelter: 0,
    volunteersNeeded: 0,
    receiverCenter: 0,
    distributionPoint: 0,
    damagedHome: 0,
    helpRequests: 0,
  },
  generatedAt: "2026-08-12T18:30:00.000Z",
  dataClassification: "demonstrative",
  items: [
    ...buildingPendingDemoPoints,
    {
      id: "cc3b061a-cc85-48cb-92f2-60ee17a26bf1",
      category: "rubble_pending",
      title: "Sector de inspección Delta",
      locationLabel: "Quetame, Cundinamarca",
      latitude: 4.329,
      longitude: -73.861,
      coordinatePrecision: "exact",
      verificationStatus: "under_review",
      relatedDisasterId: null,
      description: "Punto demostrativo pendiente de revisión por el equipo de búsqueda.",
      source: {
        name: "Coordinación operativa demo",
        sourceType: "official",
        url: null,
      },
      updatedAt: "2026-08-12T18:24:00.000Z",
    },
    {
      id: "529d75ea-2824-4c74-b206-48f586f37303",
      category: "missing_person",
      title: "Zona de búsqueda prioritaria 01",
      locationLabel: "Oriente de Cundinamarca",
      latitude: 4.363,
      longitude: -73.936,
      coordinatePrecision: "approximate",
      verificationStatus: "under_review",
      relatedDisasterId: null,
      description: "Área aproximada y anónima asociada a reportes de desaparición.",
      source: {
        name: "Puesto de mando demo",
        sourceType: "official",
        url: null,
      },
      updatedAt: "2026-08-12T18:18:00.000Z",
    },
    {
      id: "de5129a2-a6a5-44aa-9831-722a5890c320",
      category: "collection_center",
      title: "Centro de acopio Norte",
      locationLabel: "Bogotá, Distrito Capital",
      latitude: 4.731,
      longitude: -74.071,
      coordinatePrecision: "exact",
      verificationStatus: "verified",
      relatedDisasterId: null,
      description: "Punto demostrativo habilitado para recepción de agua y alimentos.",
      source: {
        name: "Logística territorial demo",
        sourceType: "official",
        url: null,
      },
      updatedAt: "2026-08-12T18:03:00.000Z",
    },
    {
      id: "a6078fee-7d38-4c91-a534-0f68ea6acf86",
      category: "rubble_reviewed",
      title: "Sector de inspección Bravo",
      locationLabel: "Chipaque, Cundinamarca",
      latitude: 4.442,
      longitude: -74.044,
      coordinatePrecision: "exact",
      verificationStatus: "verified",
      relatedDisasterId: null,
      description: "Revisión demostrativa registrada; no declara el lugar como seguro.",
      source: {
        name: "Brigada de rescate demo",
        sourceType: "official",
        url: null,
      },
      updatedAt: "2026-08-12T17:55:00.000Z",
    },
    {
      id: "61682b03-1704-455d-aa5a-3a01d5e2a9eb",
      category: "collection_center",
      title: "Centro de acopio Oriente",
      locationLabel: "Cáqueza, Cundinamarca",
      latitude: 4.405,
      longitude: -73.949,
      coordinatePrecision: "exact",
      verificationStatus: "verified",
      relatedDisasterId: null,
      description: "Punto demostrativo para recepción y clasificación inicial de recursos.",
      source: {
        name: "Logística territorial demo",
        sourceType: "official",
        url: null,
      },
      updatedAt: "2026-08-12T17:41:00.000Z",
    },
    {
      id: "c7a63803-d343-43b5-bfa8-a67d7b445210",
      category: "missing_person",
      title: "Zona de búsqueda prioritaria 02",
      locationLabel: "Villavicencio, Meta",
      latitude: 4.154,
      longitude: -73.637,
      coordinatePrecision: "municipality",
      verificationStatus: "unverified",
      relatedDisasterId: null,
      description: "Referencia municipal demostrativa sin identidad ni coordenada personal.",
      source: {
        name: "Reporte territorial demo",
        sourceType: "citizen",
        url: null,
      },
      updatedAt: "2026-08-12T17:26:00.000Z",
    },
    {
      id: "ad431dbd-6904-481d-a5d4-f32ebf1f72b2",
      category: "rubble_pending",
      title: "Sector de inspección Eco",
      locationLabel: "Guayabetal, Cundinamarca",
      latitude: 4.217,
      longitude: -73.817,
      coordinatePrecision: "exact",
      verificationStatus: "unverified",
      relatedDisasterId: null,
      description: "Ubicación demostrativa reportada para programación de revisión.",
      source: {
        name: "Reporte territorial demo",
        sourceType: "citizen",
        url: null,
      },
      updatedAt: "2026-08-12T17:12:00.000Z",
    },
    {
      id: "ad572da0-c591-4459-9aef-bd6f55c13526",
      category: "rubble_reviewed",
      title: "Sector de inspección Alfa",
      locationLabel: "Fómeque, Cundinamarca",
      latitude: 4.487,
      longitude: -73.893,
      coordinatePrecision: "exact",
      verificationStatus: "verified",
      relatedDisasterId: null,
      description: "Revisión demostrativa registrada por una brigada de búsqueda.",
      source: {
        name: "Brigada de rescate demo",
        sourceType: "official",
        url: null,
      },
      updatedAt: "2026-08-12T16:58:00.000Z",
    },
  ],
};
