import { missingPersonDemoData } from "../missing-persons/demoData";
import type {
  AidLocationDirectoryCard,
  HumanitarianDirectoryItem,
  MissingPersonDirectoryCard,
} from "./types";

export const missingPersonDirectoryDemoData: MissingPersonDirectoryCard[] =
  missingPersonDemoData.map((person) => ({
    kind: "missing_person",
    id: person.id,
    publicCaseCode: person.publicCaseCode,
    displayName: person.displayName,
    status: "missing",
    approximateAge: person.approximateAge,
    lastSeenAt: person.lastSeenAt,
    lastSeenArea: person.lastSeenArea,
    municipality: person.municipality,
    department: person.department,
    publicPhotoUrl: person.publicPhotoUrl,
    source: {
      name: "Expediente público moderado demo",
      sourceType: "citizen",
      url: null,
    },
    updatedAt: person.updatedAt,
    dataClassification: person.dataClassification,
  }));

export const aidLocationDirectoryDemoData: AidLocationDirectoryCard[] = [
  {
    kind: "collection_center",
    id: "de5129a2-a6a5-44aa-9831-722a5890c320",
    name: "Centro de acopio Norte",
    locationLabel: "Zona norte de Bogotá",
    municipality: "Bogotá",
    department: "Distrito Capital",
    verificationStatus: "verified",
    availabilityStatus: "active",
    openNow: true,
    acceptedSupplies: ["water", "food", "medicine"],
    averageRating: 4.6,
    ratingsCount: 38,
    source: {
      name: "Logística territorial demo",
      sourceType: "official",
      url: null,
    },
    updatedAt: "2026-08-14T08:30:00.000Z",
    dataClassification: "demonstrative",
  },
  {
    kind: "collection_center",
    id: "61682b03-1704-455d-aa5a-3a01d5e2a9eb",
    name: "Centro de acopio Oriente",
    locationLabel: "Corredor logístico oriental",
    municipality: "Cáqueza",
    department: "Cundinamarca",
    verificationStatus: "under_review",
    availabilityStatus: "active",
    openNow: null,
    acceptedSupplies: ["food", "clothing", "tools"],
    averageRating: 3.9,
    ratingsCount: 17,
    source: {
      name: "Reporte territorial demo",
      sourceType: "citizen",
      url: null,
    },
    updatedAt: "2026-08-14T07:45:00.000Z",
    dataClassification: "demonstrative",
  },
  {
    kind: "collection_point",
    id: "7e1979c0-470e-4a62-b8f1-f31a888c7d11",
    name: "Punto comunitario UIS",
    locationLabel: "Entrada occidental del campus",
    municipality: "Bucaramanga",
    department: "Santander",
    verificationStatus: "verified",
    availabilityStatus: "active",
    openNow: true,
    acceptedSupplies: ["water", "food", "clothing"],
    averageRating: 4.8,
    ratingsCount: 52,
    source: {
      name: "Red comunitaria demo",
      sourceType: "integration",
      url: null,
    },
    updatedAt: "2026-08-14T09:05:00.000Z",
    dataClassification: "demonstrative",
  },
  {
    kind: "collection_point",
    id: "f3ad8289-0393-466c-a650-11de1be7f537",
    name: "Punto vecinal La Esperanza",
    locationLabel: "Salón comunal del barrio",
    municipality: "Floridablanca",
    department: "Santander",
    verificationStatus: "unverified",
    availabilityStatus: "unknown",
    openNow: null,
    acceptedSupplies: ["food", "medicine", "shelter"],
    averageRating: null,
    ratingsCount: 0,
    source: {
      name: "Reporte ciudadano demo",
      sourceType: "citizen",
      url: null,
    },
    updatedAt: "2026-08-14T06:20:00.000Z",
    dataClassification: "demonstrative",
  },
];

export const humanitarianDirectoryDemoData: HumanitarianDirectoryItem[] = [
  ...missingPersonDirectoryDemoData,
  ...aidLocationDirectoryDemoData,
];
